name: highiq-dev
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - scipy
  - matplotlib
  - netcdf4
  - pytest
  - pytest-cov
  - dask
  - xarray
  - flake8
  - ipython
  - pint
  - cupy
